### ISSUE TITLE
"single color" button is not obviously a toggle

### ISSUE THREAD

**Issue by joemfox** [datadesk/Chartbuilder#42]

**Comment by joemfox** [comment]
unselected:
<img width="778" alt="screen shot 2016-05-04 at 10 17 29 am" src="https://cloud.githubusercontent.com/assets/2977115/15022634/725a4090-11e1-11e6-805a-6e2933812f29.png">
selected:
<img width="774" alt="screen shot 2016-05-04 at 10 17 24 am" src="https://cloud.githubusercontent.com/assets/2977115/15022640/782644ba-11e1-11e6-81dd-a1f36f42ed90.png">

**Comment by joemfox** [comment]
It also is not technically a toggle at all — when you click it it changes the charts to a single color but deactivating it does not change the colors back.

**Comment by emamd** [comment]
Ah I'd never noticed that button before. I don't think it even needs to be there, do you?

**Comment by joemfox** [comment]
kill it!
