### ISSUE TITLE
Encoding of apostrophes in p2p is all janked

### ISSUE THREAD

**Issue by emamd** [datadesk/Chartbuilder#51]
<img width="677" alt="screen shot 2016-05-16 at 11 53 41 am" src="https://cloud.githubusercontent.com/assets/524959/15300403/5a0a1f58-1b5d-11e6-9334-2ebe0c483db2.png">

**Comment by palewire** [comment]
We've got some hacks in liveblog and snap that handle this kind of thing. The root problem is that the P2P database is still latin-1 encoding. Those guys can help you with the patch, though to be honest we really should port the fix into the python wrapper so we don't have to implement on everything we do.

**Comment by jperezlatimes** [comment]
We have three methods in SNAP to handle encoding since we have to encode different fields at different points in the app process.  Though I agree with Ben, an overall python solution would be ideal.

Javascript to convert into/out of unicode

```
  /**
   * encodeText
   *
   * Encodes weird entities into HTML entities
   * 2nd param is true for encode, false for decode
   */
  var encodeText = function(text, encode) {
    if (typeof text != "undefined" && text != null){
      var resultText;
      if (encode == true){ //going into HTML
        resultText = text.replace(/[\u0100-\u9999]/gim, function(i) {
          return '&#'+i.charCodeAt(0)+';';
        });
      } else { //going back to weird entities
        resultText = (text+"").replace(/&#\d+;/gm,function(s) {
          return String.fromCharCode(s.match(/\d+/gm)[0]);
        });
      }
      return resultText;
    } else { //if there's no text to encode
      return "";
    }
  };
```

Python Encoding using BeautifulSoup (borrowed from @charlex)

```
from bs4 import BeautifulSoup

def clean_for_p2p(html):
     """
     This helper function returns a standardized encoding for HTML to be passed
     into p2p to avoid exceptions and upside down question marks.
     """
     soup = BeautifulSoup(html, 'html.parser')
     converted_str = soup.encode("latin-1", "xmlcharrefreplace")
     return unicode(converted_str, "latin-1")
```

Newsgate XML requires HTML entities, so we use HTML Parser to go from unicode to entities

```
import HTMLParser

h = HTMLParser.HTMLParser()
content = h.unescape(content).encode('ascii', 'xmlcharrefreplace')
```

**Comment by emamd** [comment]
the BeautifulSoup option seems like the best option. I'mma give that a try and report back.

**Comment by emamd** [comment]
<img width="1121" alt="screen shot 2016-05-16 at 1 37 15 pm" src="https://cloud.githubusercontent.com/assets/524959/15303189/56c093d2-1b6b-11e6-9c2b-1ea0e88c2e1b.png">

![](http://i.giphy.com/msKNSs8rmJ5m.gif)
