### ISSUE TITLE
Exported pngs have wrong fonts and are slightly blurry

### ISSUE THREAD

**Issue by joemfox** [datadesk/Chartbuilder#99]
example: 
![la-g-days-of-extreme-heat-could-be-curbed-by-2100-2016-06-20-chartbuilder-1](https://cloud.githubusercontent.com/assets/2977115/16250167/193b1268-37d0-11e6-954c-21bd81490802.png)

**Comment by emamd** [comment]
The fonts look the same, just slightly different due maybe to how the aliasing works when it's converted into PNG. I don't think we'll use them in a size that would make the blurriness overly visible, and it's certainly better than what is in P2P right now.
